# Generated by Django 2.1 on 2018-08-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_content',
        ),
    ]
