# Generated by Django 2.1 on 2018-08-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.TextField()),
                ('content_order', models.IntegerField()),
                ('content', models.TextField()),
                ('html_type', models.CharField(max_length=10)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=15, null=True)),
                ('class_conflict', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'article_content',
            },
        ),
        migrations.AlterUniqueTogether(
            name='article_content',
            unique_together={('article_id', 'content_order')},
        ),
    ]
